import math
from typing import Dict, List

from app.models.contracts import PatternMatch, RagEmbeddingPayload, VectorRetrievalRequest

_EMBEDDING_STORE: Dict[str, RagEmbeddingPayload] = {}

_PATTERN_METADATA: Dict[str, List[str]] = {}

_EMBEDDING_TO_PATTERN: Dict[str, str] = {}


def _text_to_naive_vector(text: str) -> List[float]:
    text_lower = text.lower()
    counts = [float(text_lower.count(chr(ord("a") + i))) for i in range(26)]
    magnitude = math.sqrt(sum(c * c for c in counts)) or 1.0
    return [c / magnitude for c in counts]
 
 
def _cosine_similarity(vec_a: List[float], vec_b: List[float]) -> float:
    """Return cosine similarity in [0.0, 1.0] between two equal-length vectors."""
    if len(vec_a) != len(vec_b):
        return 0.0
    dot = sum(a * b for a, b in zip(vec_a, vec_b))
    mag_a = math.sqrt(sum(a * a for a in vec_a)) or 1.0
    mag_b = math.sqrt(sum(b * b for b in vec_b)) or 1.0
    # Clamp to [0, 1] to avoid float rounding artefacts
    return max(0.0, min(1.0, dot / (mag_a * mag_b)))


class VectorDbVertexAiRepository:
    def upsert_embeddings(self, payloads: list[RagEmbeddingPayload]) -> None:
        """Persist embeddings generated by RAG engine into Vector DB Vertex AI."""
        for payload in payloads:
            _EMBEDDING_STORE[payload.source_id] = payload

    def upsert_embedding(self, payload: RagEmbeddingPayload) -> None:
        """Persist a single embedding generated by RAG engine into Vector DB Vertex AI."""
        _EMBEDDING_STORE[payload.source_id] = payload

    def search_nearest_neighbors(self, request: VectorRetrievalRequest) -> list[PatternMatch]:
        """Return semantic nearest-neighbor matches from Vector DB Vertex AI."""
        if not _EMBEDDING_STORE:
            return []
        
        query_vec = request.query_vector

        scored: list[PatternMatch] = []
        for source_id, payload in _EMBEDDING_STORE.items():
            if payload.vector is None:
                continue
            doc_vec = payload.vector
            similarity = _cosine_similarity(query_vec, doc_vec)
            scored.append(PatternMatch(
                pattern_id=source_id,
                pattern_text=payload.source_text,
                score=round(similarity, 4),
            ))
        scored.sort(key=lambda m: m.score, reverse=True)
        return scored[:request.topK]

    def search_embeddings(self, request: VectorRetrievalRequest) -> list[PatternMatch]:
        """Return semantic nearest-neighbor matches from Vector DB Vertex AI."""
        if not _EMBEDDING_STORE:
            return []
        
        query_vec = request.query_vector

        scored: list[PatternMatch] = []
        for source_id, payload in _EMBEDDING_STORE.items():
            if payload.vector is None:
                continue
            doc_vec = payload.vector
            similarity = _cosine_similarity(query_vec, doc_vec)
            scored.append(PatternMatch(
                pattern_id=source_id,
                pattern_text=payload.source_text,
                score=round(similarity, 4),
            ))
        scored.sort(key=lambda m: m.score, reverse=True)
        return scored[:request.topK]

    def attach_pattern_ids_to_embeddings(self, pattern_ids: list[str]) -> None:
        """Link scam-pattern metadata with vectors for later metadata resolution."""
        for pattern_id in pattern_ids:
            if pattern_id not in _PATTERN_METADATA:
                _PATTERN_METADATA[pattern_id] = []

            for source_id in _EMBEDDING_STORE:
                if pattern_id in source_id and source_id not in _PATTERN_METADATA[pattern_id]:
                    _PATTERN_METADATA[pattern_id].append(source_id)
                    _EMBEDDING_TO_PATTERN[source_id] = pattern_id

    def resolve_pattern_ids_from_embedding_hits(self, embedding_ids: list[str]) -> list[str]:
        """Resolve scam-pattern IDs from embedding match IDs returned by vector search."""
        seen: set[str] = set()
        result: list[str] = []
        for emb_id in embedding_ids:
            pattern_id = _EMBEDDING_TO_PATTERN.get(emb_id)
            if pattern_id and pattern_id not in seen:
                seen.add(pattern_id)
                result.append(pattern_id)
        return result
