from app.models.contracts import PatternMatch, RagEmbeddingPayload, VectorRetrievalRequest


class VectorDbVertexAiRepository:
    def upsert_embeddings(self, payloads: list[RagEmbeddingPayload]) -> None:
        """Persist embeddings generated by RAG engine into Vector DB Vertex AI."""
        pass

    def search_embeddings(self, request: VectorRetrievalRequest) -> list[PatternMatch]:
        """Return semantic nearest-neighbor matches from Vector DB Vertex AI."""
        pass

    def attach_pattern_ids_to_embeddings(self, pattern_ids: list[str]) -> None:
        """Link scam-pattern metadata with vectors for later metadata resolution."""
        pass

    def resolve_pattern_ids_from_embedding_hits(self, embedding_ids: list[str]) -> list[str]:
        """Resolve scam-pattern IDs from embedding match IDs returned by vector search."""
        pass
